---
- name: Include installation tasks
  include_tasks: install.yml
  tags: install

- name: Include Label Nodes tasks
  include_tasks: taint.yml
  tags: taint

- name: Include Label Nodes tasks
  include_tasks: label.yml
  tags: label

- name: Include Helm tasks
  include_tasks: helm.yml
  tags: helm

- name: Include CNI tasks
  include_tasks: cilium.yml
  tags: cilium

- name: Include Helm tasks
  include_tasks: kyverno.yml
  tags: kyverno

- name: Include CSI tasks
  include_tasks: mayastor.yml
  tags: mayastor

- name: Include Dashboard tasks
  include_tasks: dashboard.yml
  when: install_dashboard | default(false)
  tags: dashboard


